name: Lint
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install shellcheck
        run: sudo apt install shellcheck
      - name: Lint
        run: make lint
        
